/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const WoodType = IDL.Variant({
  'lineRange' : IDL.Null,
  'acaciaWood' : IDL.Null,
  'mangoWood' : IDL.Null,
  'customisedProducts' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'imageUrls' : IDL.Vec(ExternalBlob),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : IDL.Text,
  'woodType' : WoodType,
  'finishInfo' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const Time = IDL.Int;
export const ContactFormSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const CustomizationRequest = IDL.Record({
  'status' : IDL.Text,
  'name' : IDL.Text,
  'referenceImageUrl' : IDL.Opt(ExternalBlob),
  'productType' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'woodType' : WoodType,
  'dimensions' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactFormSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getCustomizationRequests' : IDL.Func(
      [],
      [IDL.Vec(CustomizationRequest)],
      ['query'],
    ),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getMangoWoodProductByIdInternal' : IDL.Func(
      [ProductId],
      [Product],
      ['query'],
    ),
  'getMangoWoodProductsInternal' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductById' : IDL.Func([ProductId], [Product], ['query']),
  'getProducts' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMangoWoodProductsInternal' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func([ContactFormSubmission], [], []),
  'submitCustomizationRequest' : IDL.Func([CustomizationRequest], [], []),
  'updateProduct' : IDL.Func([ProductId, Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const WoodType = IDL.Variant({
    'lineRange' : IDL.Null,
    'acaciaWood' : IDL.Null,
    'mangoWood' : IDL.Null,
    'customisedProducts' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'imageUrls' : IDL.Vec(ExternalBlob),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : IDL.Text,
    'woodType' : WoodType,
    'finishInfo' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const Time = IDL.Int;
  const ContactFormSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const CustomizationRequest = IDL.Record({
    'status' : IDL.Text,
    'name' : IDL.Text,
    'referenceImageUrl' : IDL.Opt(ExternalBlob),
    'productType' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'woodType' : WoodType,
    'dimensions' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactFormSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getCustomizationRequests' : IDL.Func(
        [],
        [IDL.Vec(CustomizationRequest)],
        ['query'],
      ),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getMangoWoodProductByIdInternal' : IDL.Func(
        [ProductId],
        [Product],
        ['query'],
      ),
    'getMangoWoodProductsInternal' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductById' : IDL.Func([ProductId], [Product], ['query']),
    'getProducts' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMangoWoodProductsInternal' : IDL.Func(
        [],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func([ContactFormSubmission], [], []),
    'submitCustomizationRequest' : IDL.Func([CustomizationRequest], [], []),
    'updateProduct' : IDL.Func([ProductId, Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };