/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSummary {
  'totalProducts' : bigint,
  'recentContactSubmissions' : Array<ContactFormSubmission>,
  'totalCustomizationRequests' : bigint,
  'recentCustomizationRequests' : Array<CustomizationRequest>,
  'productsByCategory' : Array<[string, Array<Product>]>,
  'inactiveProducts' : bigint,
  'totalContactSubmissions' : bigint,
  'activeProducts' : bigint,
}
export interface ContactFormSubmission {
  'id' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface CustomizationRequest {
  'id' : string,
  'status' : string,
  'name' : string,
  'referenceImageUrl' : [] | [ExternalBlob],
  'productType' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
  'woodType' : WoodType,
  'dimensions' : string,
}
export type ExternalBlob = Uint8Array;
export type ImageId = Uint8Array;
export interface PaginatedProducts {
  'total' : bigint,
  'products' : Array<Product>,
}
export interface Product {
  'id' : ProductId,
  'whatsappMessage' : [] | [string],
  'imageUrls' : Array<ImageId>,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'category' : string,
  'woodType' : WoodType,
  'finishInfo' : string,
}
export type ProductId = string;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WoodType = { 'lineRange' : null } |
  { 'acaciaWood' : null } |
  { 'mangoWood' : null } |
  { 'customisedProducts' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAnalyticsSummary' : ActorMethod<[], AnalyticsSummary>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getMostRecentContactFormSubmissions' : ActorMethod<
    [bigint],
    Array<ContactFormSubmission>
  >,
  'getMostRecentCustomizationRequests' : ActorMethod<
    [bigint],
    Array<CustomizationRequest>
  >,
  'getProductById' : ActorMethod<[ProductId], Product>,
  'getProducts' : ActorMethod<[[] | [string]], Array<Product>>,
  'getProductsGroupedByCategory' : ActorMethod<
    [],
    Array<[string, Array<Product>]>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listProducts' : ActorMethod<[bigint, bigint], PaginatedProducts>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<[ContactFormSubmission], string>,
  'submitCustomizationRequest' : ActorMethod<[CustomizationRequest], undefined>,
  'updateProduct' : ActorMethod<[ProductId, Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];